### ISSUE TITLE
put() should overwrite value if key exists

### ISSUE THREAD

**Issue by tonistiigi** [dcodeIO/btree.js#2]
At the moment when you call `put()` with same key again it just returns false and doesn't update the value. To me it seems more logical to overwrite the old value.

https://github.com/dcodeIO/btree.js/blob/72edfb5537227026ef65b7e69bc507600d43bf25/btree.js#L236

What makes it even harder is that because of the compilation phase I can't use `treenode.search()` to find the node and update the value manually. Compiler optimizes the `leaf` property away.

This would be a breaking change so I didn't make a PR yet but would like to get your thoughts.

**Comment by dcodeIO** [comment]
I agree, thanks! It's in 0.3 with an additional `overwrite` parameter that defaults to `true`.
